# Generated by Django 5.1 on 2024-09-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_order_rated_products'),
        ('products', '0004_alter_accessory_id'),
        ('stores', '0002_store_store_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.FloatField()),
                ('store_rating', models.FloatField()),
                ('review', models.CharField(max_length=256)),
                ('userId', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('store_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
