# Generated by Django 5.1 on 2024-09-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='userId',
        ),
        migrations.AddField(
            model_name='rating',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
