# Generated by Django 5.1 on 2024-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='Home', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
