# Generated by Django 5.1 on 2024-09-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=3, max_digits=4, null=True),
        ),
    ]
