# Generated by Django 5.1 on 2024-09-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('orders', '0008_remove_orderitem_address'),
        ('stores', '0002_store_store_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('order_items', models.ManyToManyField(related_name='store_orders', to='orders.orderitem')),
                ('order_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='orders.order')),
                ('store_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
