# Generated by Django 5.1 on 2024-09-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_product_id_orderitem_product_and_more'),
        ('stores', '0003_storeorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='order_items',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_order', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='order_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='orders.order'),
        ),
    ]
