# Generated by Django 5.1 on 2024-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_product_id_orderitem_product_and_more'),
        ('stores', '0004_remove_storeorder_order_items_storeorder_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='order_item',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='order_items',
            field=models.ManyToManyField(blank=True, related_name='store_orders', to='orders.orderitem'),
        ),
    ]
