# Generated by Django 5.1 on 2024-09-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storeorder_order_item_storeorder_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='order_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='store_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
