# Generated by Django 5.1 on 2024-09-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_store_logo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_title',
        ),
    ]
