# Generated by Django 5.1 on 2024-09-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_address_orderitem_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
    ]
