# Generated by Django 5.1 on 2024-09-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderitem_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='size',
            new_name='capacity',
        ),
    ]
