# Generated by Django 5.1 on 2024-09-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_accessory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
